Shopify_Store: Shopify Store
Shopify_API: Shopify API
Inventory_Translator: Inventory Translator app:

Shopify_Store -> Shopify_API: 1. notifies {
  style: {
    animated: true
  }
}
Shopify_API -> Inventory_Translator: 2. send a webhook {
  style: {
    animated: true
  }
}
