direction: right

created -> started: Unqueue 

generating: {
  style {
  stroke-dash: 3
  }
}

started -> cloning: Clone
cloning -> installing: Install
installing -> generating: Generate
generating -> compiling: Compile
compiling -> publishing: Publish
publishing -> succeeded: Success

installing -> failed: Fail
generating -> failed: Fail
compiling -> failed: Fail
