direction: right

Your Codebase -> Defer: "Enqueue execution" {
  style: {
    animated: true
  }
}

Your Codebase: {
  grid-columns: 1

  Defer Functions
  Application Code
}

Defer: {
  label.near: outside-top-center

  grid-columns: 3
  api: API {
    height: 200
  }

  scheduler

  runner: {
    style: {
      multiple: true
    }
  }

  builder: {
    style: {
      multiple: true
    }
  }
}
